DROP TABLE vvwdbadk_wikicontacts.`countrycodes`;

CREATE TABLE vvwdbadk_wikicontacts.`countrycodes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country` varchar(255) DEFAULT NULL,
  `countryCode` varchar(255) DEFAULT NULL,
  `isoCountryCode` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Afghanistan','93','AF');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Albania','355','AL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Algeria','213','DZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('American Samoa','1684','AS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Andorra','376','AD');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Angola','244','AO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Anguilla','1264','AI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Antarctica','672','AQ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Antigua and Barbuda','1268','AG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Argentina','54','AR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Armenia','374','AM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Aruba','297','AW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Australia','61','AU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Austria','43','AT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Azerbaijan','994','AZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bahamas','1242','BS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bahrain','973','BH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bangladesh','880','BD');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Barbados','1246','BB');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Belarus','375','BY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Belgium','32','BE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Belize','501','BZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Benin','229','BJ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bermuda','1441','BM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bhutan','975','BT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bolivia','591','BO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bosnia and Herzegovina','387','BA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Botswana','267','BW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Brazil','55','BR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('British Virgin Islands','1284','VG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Brunei','673','BN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Bulgaria','359','BG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Burkina Faso','226','BF');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Burma (Myanmar)','95','MM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Burundi','257','BI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cambodia','855','KH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cameroon','237','CM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Canada','1','CA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cape Verde','238','CV');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cayman Islands','1345','KY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Central African Republic','236','CF');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Chad','235','TD');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Chile','56','CL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('China','86','CN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Christmas Island','61','CX');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cocos (Keeling) Islands','61','CC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Colombia','57','CO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Comoros','269','KM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cook Islands','682','CK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Costa Rica','506','CR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Croatia','385','HR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cuba','53','CU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Cyprus','357','CY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Czech Republic','420','CZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Democratic Republic of the Congo','243','CD');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Denmark','45','DK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Djibouti','253','DJ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Dominica','1767','DM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Dominican Republic','1809','DO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Ecuador','593','EC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Egypt','20','EG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('El Salvador','503','SV');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Equatorial Guinea','240','GQ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Eritrea','291','ER');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Estonia','372','EE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Ethiopia','251','ET');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Falkland Islands','500','FK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Faroe Islands','298','FO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Fiji','679','FJ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Finland','358','FI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('France','33','FR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('French Polynesia','689','PF');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Gabon','241','GA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Gambia','220','GM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Gaza Strip / West Bank','970','PS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Georgia','995','GE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Germany','49','DE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Ghana','233','GH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Gibraltar','350','GI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Greece','30','GR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Greenland','299','GL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Grenada','1473','GD');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Guam','1671','GU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Guatemala','502','GT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Guinea','224','GN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Guinea-Bissau','245','GW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Guyana','592','GY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Haiti','509','HT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Holy See (Vatican City)','39','VA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Honduras','504','HN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Hong Kong','852','HK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Hungary','36','HU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Iceland','354','IS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('India','91','IN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Indonesia','62','ID');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Iran','98','IR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Iraq','964','IQ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Ireland','353','IE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Isle of Man','44','IM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Israel','972','IL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Italy','39','IT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Ivory Coast','225','CI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Jamaica','1876','JM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Japan','81','JP');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Jordan','962','JO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Kazakhstan','7','KZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Kenya','254','KE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Kiribati','686','KI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Kosovo','381','XK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Kuwait','965','KW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Kyrgyzstan','996','KG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Laos','856','LA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Latvia','371','LV');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Lebanon','961','LB');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Lesotho','266','LS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Liberia','231','LR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Libya','218','LY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Liechtenstein','423','LI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Lithuania','370','LT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Luxembourg','352','LU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Macau','853','MO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Macedonia','389','MK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Madagascar','261','MG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Malawi','265','MW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Malaysia','60','MY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Maldives','960','MV');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Mali','223','ML');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Malta','356','MT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Marshall Islands','692','MH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Mauritania','222','MR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Mauritius','230','MU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Mayotte','262','YT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Mexico','52','MX');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Micronesia','691','FM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Moldova','373','MD');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Monaco','377','MC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Mongolia','976','MN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Montenegro','382','ME');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Montserrat','1664','MS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Morocco','212','MA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Mozambique','258','MZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Namibia','264','NA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Nauru','674','NR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Nepal','977','NP');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Netherlands','31','NL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Netherlands Antilles','599','AN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('New Caledonia','687','NC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('New Zealand','64','NZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Nicaragua','505','NI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Niger','227','NE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Nigeria','234','NG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Niue','683','NU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Norfolk Island','672','NF');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('North Korea','850','KP');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Northern Mariana Islands','1670','MP');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Norway','47','NO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Oman','968','OM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Pakistan','92','PK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Palau','680','PW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Panama','507','PA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Papua New Guinea','675','PG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Paraguay','595','PY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Peru','51','PE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Philippines','63','PH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Pitcairn Islands','870','PN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Poland','48','PL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Portugal','351','PT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Puerto Rico','1','PR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Qatar','974','QA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Republic of the Congo','242','CG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Romania','40','RO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Russia','7','RU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Rwanda','250','RW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saint Barthelemy','590','BL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saint Helena','290','SH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saint Kitts and Nevis','1869','KN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saint Lucia','1758','LC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saint Martin','1599','MF');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saint Pierre and Miquelon','508','PM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saint Vincent and the Grenadines','1784','VC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Samoa','685','WS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('San Marino','378','SM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Sao Tome and Principe','239','ST');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Saudi Arabia','966','SA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Senegal','221','SN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Serbia','381','RS');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Seychelles','248','SC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Sierra Leone','232','SL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Singapore','65','SG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Slovakia','421','SK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Slovenia','386','SI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Solomon Islands','677','SB');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Somalia','252','SO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('South Africa','27','ZA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('South Korea','82','KR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Spain','34','ES');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Sri Lanka','94','LK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Sudan','249','SD');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Suriname','597','SR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Swaziland','268','SZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Sweden','46','SE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Switzerland','41','CH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Syria','963','SY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Taiwan','886','TW');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Tajikistan','992','TJ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Tanzania','255','TZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Thailand','66','TH');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Timor-Leste','670','TL');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Togo','228','TG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Tokelau','690','TK');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Tonga','676','TO');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Trinidad and Tobago','1868','TT');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Tunisia','216','TN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Turkey','90','TR');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Turkmenistan','993','TM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Turks and Caicos Islands','1649','TC');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Tuvalu','688','TV');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Uganda','256','UG');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Ukraine','380','UA');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('United Arab Emirates','971','AE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('United Kingdom','44','GB');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('United States','1','US');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Uruguay','598','UY');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('US Virgin Islands','1340','VI');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Uzbekistan','998','UZ');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Vanuatu','678','VU');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Venezuela','58','VE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Vietnam','84','VN');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Wallis and Futuna','681','WF');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Yemen','967','YE');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Zambia','260','ZM');
INSERT INTO vvwdbadk_wikicontacts.countrycodes (country, countryCode, isoCountryCode) VALUES ('Zimbabwe','263','ZW');